# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Python Blacken
      uses: piotrpawlaczek/python-blacken@release/stable
    - name: Python Vulture Action
      uses: anaynayak/python-vulture-action@v1.0
    - name: test2
      run: |
         python main.py
 
